# Generated by Django 3.1.7 on 2021-06-25 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_pic'),
        ('users', '0002_auto_20210611_0808'),
    ]

    operations = [
    ]
