# Generated by Django 3.2.3 on 2021-05-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210521_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytime',
            name='day',
            field=models.CharField(choices=[('monday', 'Segunda-feira'), ('tuesday', 'Terça-feira'), ('wednesday', 'Quarta-feira'), ('thursday', 'Quinta-feira'), ('friday', 'Sexta-feira'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], default=('monday', 'Segunda-feira'), max_length=15),
        ),
        migrations.AlterField(
            model_name='deliverytime',
            name='service_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.serviceaddress'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
