# Generated by Django 3.2.3 on 2021-07-04 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210628_0812'),
        ('users', '0005_user_delivery_price'),
    ]

    operations = [
    ]
