# Generated by Django 3.2.3 on 2021-06-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store_status',
            field=models.CharField(blank=True, default='Fechado', max_length=8, null=True),
        ),
    ]
