# Generated by Django 3.2.3 on 2021-06-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_merge_20210625_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('C', 'Dinheiro'), ('CC', 'Cartão de crédito'), ('DC', 'Cartão de débito')], max_length=2),
        ),
    ]
