# Generated by Django 3.1.7 on 2021-06-30 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210628_0113'),
        ('orders', '0005_auto_20210628_0812'),
    ]

    operations = [
    ]
