# Generated by Django 3.2.3 on 2021-07-01 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210628_0812'),
        ('orders', '0006_auto_20210628_0113'),
    ]

    operations = [
    ]
