# Generated by Django 3.2.3 on 2021-07-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_merge_0005_auto_20210628_0812_0006_auto_20210628_0113'),
        ('orders', '0008_auto_20210630_2043'),
    ]

    operations = [
    ]
