# Generated by Django 3.2.3 on 2021-06-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('variety', models.CharField(blank=True, max_length=200, null=True)),
                ('expiration_days', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('stock_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
