# Generated by Django 3.1.7 on 2021-06-25 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_pic'),
        ('products', '0004_favorite'),
    ]

    operations = [
    ]
