# Generated by Django 3.2.3 on 2021-05-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210526_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sale_description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
