# Generated by Django 3.2.3 on 2021-05-28 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210527_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_seller',
            field=models.IntegerField(default=1),
        ),
    ]
