# Generated by Django 3.2.3 on 2021-05-28 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def remove_empty_delivery_time(apps, schema_editor):
    try:
        DeliveryTime = apps.get_model('users', 'DeliveryTime')
        DeliveryTime.objects.filter(service_address=None).delete()
    except Exception as e:
        print(f"An error occurred on migrate 0007. {e}")


def remove_empty_address(apps, schema_editor):
    try:
        Address = apps.get_model('users', 'Address')
        Address.objects.all().delete()
    except Exception as e:
        print(f"An error occurred on migrate 0007. {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210527_2218'),
    ]
    operations = [
        migrations.RunPython(remove_empty_delivery_time),
        migrations.RunPython(remove_empty_address),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deliverytime',
            name='service_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.serviceaddress'),
        ),
        migrations.AlterField(
            model_name='serviceaddress',
            name='state',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=('AC', 'Acre'), max_length=2),
        ),
        migrations.AlterField(
            model_name='serviceaddress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
