# Generated by Django 3.2.3 on 2021-06-02 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210527_2255'),
        ('users', '0007_auto_20210528_1812'),
    ]

    operations = [
    ]
