# Generated by Django 3.2.3 on 2021-06-02 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_0004_auto_20210527_2255_0007_auto_20210528_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytime',
            name='service_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.serviceaddress'),
        ),
    ]
