# Generated by Django 3.2 on 2021-06-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210531_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_status',
            field=models.CharField(blank=True, choices=[('A', 'Aprovado'), ('R', 'Reprovado'), ('P', 'Pendente'), ('I', 'Inativo')], max_length=1, null=True),
        ),
    ]
