# Generated by Django 3.1.7 on 2021-06-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210531_2102'),
        ('users', '0009_user_seller_status'),
    ]

    operations = [
    ]
