# Generated by Django 3.2.3 on 2021-06-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210607_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_status',
            field=models.CharField(blank=True, choices=[('A', 'Aberto'), ('F', 'Fechado')], max_length=1, null=True),
        ),
    ]
