# Generated by Django 3.2.3 on 2021-06-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_store_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store_status',
            field=models.CharField(blank=True, choices=[('A', 'Aberto'), ('F', 'Fechado')], default='F', max_length=1, null=True),
        ),
    ]
