# Generated by Django 3.1.7 on 2021-06-25 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210621_2015'),
        ('orders', '0002_auto_20210624_2309'),
    ]

    operations = [
    ]
