# Generated by Django 3.2.3 on 2021-06-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Em Espera'), (1, 'Sendo preparado'), (2, 'Em rota de entrega'), (3, 'Concluído'), (4, 'Cancelado')]),
        ),
    ]
