# Generated by Django 3.2.3 on 2021-06-10 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210607_2304'),
        ('products', '0004_auto_20210608_2037'),
    ]

    operations = [
    ]
